apiVersion: v2
name: simple-container
description: >-
  Minimal, strict-by-default, Helm chart for simple stateless web containers.
  Copy the values file, change the image (and containerPort), and deploy.
type: application
version: 0.2.0
keywords:
  - web
  - container
  - security
  - restricted
  - template
